StaffReporting/Models/Work.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Management.Models
{
    public partial class Work
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Project Name")]
        public string? Title { get; set; }
        [Required]
        public string? Description { get; set; }
        public string? Priority { get; set; }
        public string? Code { get; set; }
        [Required]
        [Display(Name = "Assign a Manager")]
        public int UserId { get; set; }

        [Required]
        [Display(Name = "Department")]
        public int DeptId { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string? UpdateBy { get; set; }
        public DateTime UpdateDate { get; set; }
        public bool IsActive { get; set; } = true;
        public bool IsDelete { get; set; } = false;
        public bool IsComplete { get; set; } = false;
        public DateTime? DeadLine { get; set; }

        public List<WriteUp> WriteUps { get; set; } = new List<WriteUp>();

        [ForeignKey("UserId")]

        public virtual Users? Users { get; set; }

        [ForeignKey("DeptId")]
        public virtual Dept? Dept { get; set; }
    }
    public partial class WriteUp
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Project Name")]
        public int WorkId { get; set; }
        public string? CreatedBy { get; set; }
        public int UserId { get; set; }
        [Required]
        [Display(Name = "Remark")]
        public string? Remark { get; set; }
        [Required]
        [Display(Name = "Task Name")]
        public int Task { get; set; }
        public DateTime SubmittedDate { get; set; }
        public bool IsActive { get; set; } = true;
        [Required]
        public List<Linkpaths> Linkpaths { get; set; } = new List<Linkpaths>();

        public List<Comment> Comment { get; set; } = new List<Comment>();

        [ForeignKey("UserId")]
        public virtual Users Users { get; set; }

        [ForeignKey("WorkId")]
        public virtual Work Work { get; set; }

        [ForeignKey("Task")]
        public virtual Tasklist? Tasklist { get; set; }
    }
    public partial class Users
    {
        [Key]
        public int UserId { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Full Name")]
        public string Username { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Password")]
        public string PasswordHash { get; set; }

        [Required]
        public int DesiId { get; set; }

        [Required]
        [StringLength(20)]
        public string Role { get; set; } = "User";

        [Required]
        [EmailAddress]
        [StringLength(100)]
        public string Email { get; set; }

        [Required]
        [StringLength(100)]
        public string? Mobile { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [Required]
        public DateTime UpdateDate { get; set; } = DateTime.UtcNow;
        [Required]
        public bool IsActive { get; set; } = true;
        public bool IsDelete { get; set; } = false;

        public bool permission { get; set; } = false;

        [ForeignKey("DesiId")]
        public virtual Desi? Desi { get; set; }
    }

    public partial class Linkpaths
    {
        [Key]
        public int AttachmentId { get; set; }
        public int WriteUpId { get; set; }
        public string? Link { get; set; }
    }
    public partial class Desi
    {
        [Key]
        public int DesiId { get; set; }
        [Display(Name = "Designation Name")]
        public string? DesiName { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        public bool IsActive { get; set; } = true;
        public bool IsDelete { get; set; } = false;
    }
    public partial class Dept
    {
        [Key]
        public int DeptId { get; set; }
        [Display(Name = "Department Name")]
        public string? DeptName { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        public bool IsActive { get; set; } = true;
        public bool IsDelete { get; set; } = false;
    }
    public partial class Comment
    {
        [Key]
        public int CommentID { get; set; }
        public string? CommentText { get; set; }
        public DateTime CommentDate { get; set; } = DateTime.UtcNow;
        public int UserId { get; set; }
        public int WriteUpId { get; set; }
        public bool CommentRead { get; set; }

        [ForeignKey("UserId")]
        public virtual Users? Users { get; set; }
    }
    public partial class Tasklist
    {
        [Key]
        public int TaskID { get; set; }
        public string? TaskName { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        public bool IsActive { get; set; } = true;
        public bool IsDelete { get; set; } = false;
    }
    public partial class WorkAssignment
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [ForeignKey("Work")]
        public int WorkId { get; set; }
        public virtual Work? Work { get; set; }

        [Required]
        [ForeignKey("Users")]
        public int UserId { get; set; }
        public virtual Users User { get; set; }
    }
    public partial class ProjectAssignUser
    {
        public int UserID { get; set; }
        public string? UserName { get; set; }
        public string? Designation { get; set; }
    }        
}

StaffReporting/Areas/User/Controllers/DashboardController.cs
using Management.Data;
using Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace Management.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User,Default")]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
        public DashboardController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

StaffReporting/Controllers/ReportController.cs
using Management.Data;
using Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.EntityFrameworkCore;

namespace Management.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Manager")]
    public class ReportController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ApplicationDbContext _context;
        private readonly ICompositeViewEngine _viewEngine;
        public ReportController(ApplicationDbContext context, IWebHostEnvironment environment, ICompositeViewEngine viewEngine)
        {
            _environment = environment;
            _context = context;
            _viewEngine = viewEngine; // Inject the view engine
        }
        public IActionResult Index(int page = 1, int? TaskID = null, int? UserId = null, int? CommentID = null, int? WriteUpId = null, int? WorkId = null, int? DeptId = null, string sortOrder = "date_desc", DateTime? FromDate = null, DateTime? ToDate = null)
        {
            int pageSize = 50; // Number of records per page
            ViewBag.Task = _context.Tasklist.Where(x => x.IsActive == true && x.IsDelete == false)
                .Select(u => new SelectListItem
                {
                    Value = u.TaskID.ToString(),
                    Text = u.TaskName,
                    Selected = TaskID.HasValue && u.TaskID == TaskID.Value
                })
                .ToList();
            // Populate ViewBag.User with a list of users for the dropdown
            ViewBag.Dept = _context.Dept.Where(x => x.IsActive == true && x.IsDelete == false)
                .Select(u => new SelectListItem
                {
                    Value = u.DeptId.ToString(),
                    Text = u.DeptName,
                    Selected = DeptId.HasValue && u.DeptId == DeptId.Value
                })
                .ToList();

            // Populate ViewBag.User with a list of users for the dropdown
            ViewBag.User = _context.Users.Where(x => x.IsActive == true && x.IsDelete == false)
                .Select(u => new SelectListItem
                {
                    Value = u.UserId.ToString(),
                    Text = u.Username + "-(" + u.Desi.DesiName + ')',
                    Selected = UserId.HasValue && u.UserId == UserId.Value
                })
                .ToList();

            // Populate ViewBag.Work with a list of work titles for the dropdown
            ViewBag.Work = _context.Works.Include(x => x.Dept).Where(x => x.IsActive == true && x.IsDelete == false)
                .Select(w => new SelectListItem
                {
                    Value = w.Id.ToString(),
                    Text = w.Code + '-' + w.Title + '-' + w.Dept.DeptName,
                    Selected = WorkId.HasValue && w.Id == WorkId.Value
                })
                .ToList();

            ViewBag.SortOrderList = new List<SelectListItem>
                   {
                       new SelectListItem { Value = "date_asc", Text = "Date (Ascending)", Selected = sortOrder == "date_asc" },
                       new SelectListItem { Value = "date_desc", Text = "Date (Descending)", Selected = sortOrder == "date_desc" },
                       new SelectListItem { Value = "username_asc", Text = "Username (Ascending)", Selected = sortOrder == "username_asc" },
                       new SelectListItem { Value = "username_desc", Text = "Username (Descending)", Selected = sortOrder == "username_desc" },
                       new SelectListItem { Value = "project_asc", Text = "Project (Ascending)", Selected = sortOrder == "project_asc" },
                       new SelectListItem { Value = "project_desc", Text = "Project (Descending)", Selected = sortOrder == "project_desc" },
                   };

            // Store sorting order in ViewBag for maintaining state in the view
            ViewBag.SortOrder = sortOrder;

            // Initialize the query as IQueryable<WriteUp>
            IQueryable<WriteUp> query = _context.WriteUps
                .Include(x => x.Work).ThenInclude(w => w.Dept)
                .Include(x => x.Work).ThenInclude(w => w.Users)
                .Include(x => x.Users).ThenInclude(w => w.Desi)
                .Include(z => z.Linkpaths)
                .Include(z => z.Tasklist)
                .Include(a => a.Comment).ThenInclude(l => l.Users);

            // Apply the filter if UserId is provided
            if (UserId.HasValue)
            {
                query = query.Where(q => q.UserId == UserId.Value);
            }
            if (CommentID.HasValue)
            {
                var data = _context.Comment.FirstOrDefault(x => x.CommentID == CommentID.Value);
                if (data != null)
                {
                    data.CommentRead = true;
                    _context.SaveChanges();
                }
            }

            // Apply the filter if WorkId is provided
            if (WriteUpId.HasValue)
            {
                query = query.Where(q => q.Id == WriteUpId.Value);
            }
            if (TaskID.HasValue)
            {
                query = query.Where(q => q.Tasklist.TaskID == TaskID.Value);
            }
            // Apply the filter if WorkId is provided
            if (WorkId.HasValue)
            {
                query = query.Where(q => q.Work.Id == WorkId.Value);
            }
            if (DeptId.HasValue)
            {
                query = query.Where(q => q.Work.DeptId == DeptId.Value);
            }
            // Apply the filter if endDate is provided
            if (FromDate.HasValue)
            {
                query = query.Where(q => q.SubmittedDate >= FromDate.Value);
            }
            if (ToDate.HasValue)
            {
                query = query.Where(q => q.SubmittedDate <= ToDate.Value);
            }
            // Apply ordering based on the sortOrder parameter
            query = sortOrder switch
            {
                "date_asc" => query.OrderBy(q => q.SubmittedDate),
                "username_asc" => query.OrderBy(q => q.Users.Username),
                "username_desc" => query.OrderByDescending(q => q.Users.Username),
                "project_asc" => query.OrderBy(q => q.Work.Title),
                "project_desc" => query.OrderByDescending(q => q.Work.Title),
                _ => query.OrderByDescending(q => q.SubmittedDate), // Default to date ascending
            };

            // Get the total count of filtered records
            int totalRecords = query.Count();
            // Pass data to the view
            ViewBag.CurrentPage = page;
            ViewBag.SelectedUserId = UserId;
            ViewBag.SelectedWorkId = WorkId;
            ViewBag.SelectedDeptId = DeptId;
            ViewBag.FromDate = FromDate;
            ViewBag.ToDate = ToDate;
            // Handle no records scenario
            if (totalRecords == 0)
            {
                ViewBag.CurrentPage = 1;
                ViewBag.TotalPages = 1;
                if (WorkId.HasValue)
                {
                    int idd = WorkId ?? 0;
                    ViewBag.workdata = _context.Works.Where(x => x.Id == WorkId).FirstOrDefault();
                }
                return View(new List<WriteUp>());
            }

            // Calculate the total number of pages
            int totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);

            // Ensure the requested page is within valid range
            if (page < 1) page = 1;
            if (page > totalPages) page = totalPages;

            // Fetch the paginated data
            var writeUps = query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.TotalPages = totalPages;
            return View(writeUps);
        }
    }
}

StaffReporting/Areas/Manager/Views/Work/Index.cshtml
@model IEnumerable<Management.Models.WriteUp>



<form asp-action="Index" method="get">
	<div class="row g-3 justify-content-between align-items-center">
		<!-- Submit New Report Button -->
		<div class="col-lg-3 col-md-6 col-sm-12">
			<a asp-action="WriteUp" class="btn btn-primary w-100">
				<i class="fa fa-plus"></i> Add New Report
			</a>
		</div>

		<!-- Filter by Project Dropdown -->
		<div class="col-lg-3 col-md-6 col-sm-12">
			<select id="WorkId" name="WorkId" class="select-work form-select w-100" asp-items="ViewBag.Work">
				<option value="">Select a Project</option>
			</select>
		</div>

		<!-- Sort Order Dropdown -->
		<div class="col-lg-3 col-md-6 col-sm-12 text-md-end">
			<select id="sortOrder" name="sortOrder" class="form-select w-100" asp-items="ViewBag.SortOrderList">
				<option value="">Sort by</option>
			</select>
		</div>

		<!-- Search Button -->
		<div class="col-lg-3 col-md-6 col-sm-12">
			<button type="submit" class="btn btn-primary w-100">View</button>
		</div>
	</div>

</form>


<div class="row">
	<div class="col-md-12">
		@if (Model != null && Model.Any())
		{
			<div class="card mt-3">
				<div class="card-header">
					<h5 class="text-uppercase mt-3">Report - @Model.First().Users.Username - (@Model.First().Users.Desi.DesiName)</h5>
				</div>
			</div>
			foreach (var task in Model)
			{
				<div class="card mb-3">
					<div class="card-body" style="margin-top:-12px !important">
						<!-- Task Details -->
						<div class="row">
							<div class="col-md-12 card-header">
								<h5>
									<strong>Date: @task.SubmittedDate.ToShortDateString()</strong>
									| <strong>Project:</strong><a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" asp-area="" asp-controller="Report" asp-action="Index" asp-route-WorkId="@task.Work.Id">
										@task.Work.Code-@task.Work.Title @if (task.Work.IsComplete)
										{
											<i class="fa fa-check" style="color: green;" aria-hidden="true"></i>
										}
									</a>
								</h5>
								<h6 class="text-black-50">
									<strong>Department:</strong> @task.Work.Dept.DeptName
									| <strong>Reporting to:</strong> @task.Work.Users.Username
									| <strong>Task:</strong> @task.Tasklist.TaskName | <strong>Designation:</strong> @task.Users.Desi.DesiName
								</h6>
							</div>
							<div class="col-md-12 mt-3">
								<strong class="text-uppercase">Remark:</strong>
								<p>@Html.Raw(task.Remark)</p>
								@if (task.Linkpaths != null && task.Linkpaths.Any())
								{
									<h6>Attached Files:</h6>
									int i = 1;
									@foreach (var item in task.Linkpaths)
									{
										<a href="@Url.Content($"~/uploads/{System.IO.Path.GetFileName(item.Link)}")" target="_blank" class="btn btn-link">attached-@i</a>
										i++;
									}
								}
							</div>
							<!-- Comments Section -->
							<div class="col-md-12 mt-3">
								<div id="comments-section-@task.Id">
									@await Html.PartialAsync("_CommentsPartial", task.Comment)
								</div>
							</div>
							<!-- Add Comment Button -->
							<div class="col-md-12 mt-3">
								<button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#commentModal-@task.Id">Add Comment</button>
							</div>
						</div>
					</div>
				</div>

				<!-- Comment Modal -->
				<div class="col-md-12 mt-3">
					@await Html.PartialAsync("_CommentModalPartial", task.Id)
				</div>
			}

			<!-- Pagination -->
			<div>
				<nav aria-label="Page navigation">
					<ul class="pagination">
						@if (ViewBag.TotalPages > 1)
						{
							@for (int i = 1; i <= ViewBag.TotalPages; i++)
							{
								<li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
									<a class="page-link" href="@Url.Action("Index", new { page = i, UserId = ViewBag.SelectedUserId })">@i</a>
								</li>
							}
						}
					</ul>
				</nav>
			</div>
		}
		else
		{
			<div class="d-flex justify-content-center align-items-center mt-5">
				<div class="text-center">
					<h5><i class="fa fa-ban"></i> No remark found.</h5>
				</div>
			</div>
		}
	</div>
</div>

StaffReporting/Areas/Manager/Views/Work/WriteUp.cshtml
@model Management.Models.WriteUp

<h2>Submit New Report</h2>
<style>
    /* Page opacity effect */
    .dimmed {
        opacity: 0.5;
        pointer-events: none; /* Prevent interactions while loading */
    }
</style>
<div id="loader" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 9999; background: rgba(255, 255, 255, 0.8); padding: 20px; border-radius: 5px;">
    <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <p style="text-align: center; margin-top: 10px;">Loading, please wait...</p>
</div>

<form asp-action="WriteUp" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    <div class="row mb-3">
        <div class="col-md-6">
            <label class="form-label" asp-for="WorkId">Select a Project</label>
            <select asp-for="WorkId" class="form-select select-work" asp-items="@ViewBag.Project">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="WorkId" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <label class="form-label" asp-for="Task">Select Task</label>
            <select asp-for="Task" class="form-select" asp-items="@ViewBag.Tasklist">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="Task" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-9">
            <label class="form-label" asp-for="Remark">Add Remark</label>
            <textarea asp-for="Remark" id="editor" class="form-control summernote" required></textarea>
            <span asp-validation-for="Remark" class="text-danger"></span>
        </div>
        <div class="col-md-3">
            <label class="form-label">Upload Multiple Files</label>
            <div id="fileUploadContainer">
                <input type="file" class="form-control mb-2" name="files" onchange="addFileInput(this)" />
            </div>
            <span asp-validation-for="Linkpaths" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            <a asp-controller="Dashboard" asp-action="Index" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary" id="submitButton">Submit</button>
        </div>
    </div>
</form>


@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const loader = document.getElementById('loader');
            const body = document.body;
            const form = document.querySelector('form');

            // Handle form submission
            form.addEventListener('submit', function (event) {
                // Check form validity
                if (!form.checkValidity()) {
                    event.preventDefault(); // Prevent submission
                    event.stopPropagation(); // Stop further event propagation
                    form.classList.add('was-validated'); // Add validation feedback
                    console.log('Form is invalid. Loader not shown.');
                    return; // Exit early on invalid form
                }

                console.log('Form is valid. Showing loader.');
                loader.style.display = 'block'; // Show the loader
                body.classList.add('dimmed'); // Apply the dimmed effect to the page
            }, false);

            // Prevent accidental double submission
            form.addEventListener('submit', function () {
                const submitButton = document.getElementById('submitButton');
                if (submitButton) {
                    submitButton.disabled = true; // Disable the button after submission
                }
            });
        });
    </script>
    <script>
        function addFileInput(inputElement) {
            // Check if the current input has a file selected
            if (inputElement.files.length > 0) {
                // Create a new input element
                const newInput = document.createElement('input');
                newInput.type = 'file';
                newInput.name = 'files';
                newInput.className = 'form-control mb-2';
                newInput.onchange = function () {
                    addFileInput(newInput); // Add new input when a file is selected
                };

                // Append the new input element to the file upload container
                const container = document.getElementById('fileUploadContainer');
                container.appendChild(newInput);
            }
        }
    </script>
}